### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/seqkit#1]
- [x] add subcommand to reset start position for circular genome, like [fasta_reset_start_position_for_circular_genome.pl](https://github.com/shenwei356/bio_scripts/blob/master/sequence/fasta_reset_start_position_for_circular_genome.pl)
- [x] `seqkit stat` or add a new command `seqkit stat2`, add N50, N90.. column for FASTA file
- [x] filter sequence by sequence length
- [x] `seqkit seq -g -G ` and `seqkit stat -a -g` : bug when given non-ASCII gaps letters

**Comment by shenwei356** [comment]
seq -g and stat -a : bug when given non ascii gaps letters

**Comment by ctava** [comment]
@shenwei356 are these TODOs current? if so, could they be broken down into multiple issues?
